# Generated by Django 3.0.5 on 2020-04-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200419_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Ожидают'), ('Out for delivery', 'На доставке'), ('Delivered', 'Доставлен')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'В кафе'), ('Out door', 'С собой')], max_length=200, null=True, verbose_name='Категория'),
        ),
    ]
